module: src.client.agents.HTTPAgent
parameters:
  url: https://api.openai.com/v1/chat/completions
  headers:
    Content-Type: application/json
    Authorization: Bearer <% PUT-YOUR-OPENAI-KEY-HERE %>
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]} prompt_tokens: {response[usage][prompt_tokens]} completion_tokens: {response[usage][completion_tokens]}"
