import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    os-std: 5
    alfworld-std: 5
    cg-std: 5
    kg-std: 5
    ltp-std: 5
    m2w-std: 5
    webshop-std: 5

  agent:
    gpt-3.5-turbo: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-3.5-turbo
    task:
      # - os-std
      # - dbbench-std
      # - alfworld-std
      # - cg-std
      # - kg-std
      # - ltp-std
      # - m2w-std
      # - webshop-std

output: "outputs/{TIMESTAMP}"
